// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;

namespace PC4_ML
{
    public partial class MLRecomendation
    {
        /// <summary>
        /// Clase de entrada del modelo para MLRecomendation.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"productoId")]
            public float ProductoId { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"interes")]
            public float Interes { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"usuarioId")]
            public float UsuarioId { get; set; }
        }
        #endregion

        /// <summary>
        /// Clase de salida del modelo para MLRecomendation.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"productoId")]
            public float ProductoId { get; set; }

            [ColumnName(@"interes")]
            public float Interes { get; set; }

            [ColumnName(@"usuarioId")]
            public float UsuarioId { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLRecomendation.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Utiliza este método para predecir con <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">Entrada del modelo.</param>
        /// <returns><seealso cref="ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
